server:
  port: 8081

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: message

  mvc:
    view:
      prefix: /WEB-INF/views/  # 변경가능
      suffix: .jsp

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: security
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.restuserservice.domain

token:
  expiration_time: 86400000
  secret: user_token